# Generated by Django 5.1.3 on 2024-11-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='my_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
