# Generated by Django 5.1.3 on 2024-11-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_alter_album_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='my_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
